name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Build library and tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install sdl2 and vorbis
      run: sudo apt install -y libsdl2-dev libvorbis-dev
    - name: pull submodules
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init --recursive
    - name: make libDuEngine
      run: make libDuEngine.so
    - name: make test
      run: make test
